Add option to wait for signald.send() confirmation
lwesterhof/semaphore pull request #30
Opened 2021-02-13 00:08 UTC by eknoes

Resolves #28 

I use 2 different sockets for now, so we do not interfere with receiving messages if waiting for a response to our send message. This PR makes `send_message -> bool` and logs warnings if a message could not be sent.

We could also add this for `reply_message` or do you think this is not really necessary?

2021-02-13 00:10 UTC, eknoes commented on semaphore/message_sender.py
> +                    return False
I am not really confident with Pythons async behaviour, but could this here lead to a race condition, when 2 messages are sent but the second one is confirmed earlier by signald?

2021-02-19 07:03 UTC, lwesterhof requested changes
It looks like you are not using the id field of signald (https://gitlab.com/signald/signald/-/issues/84). Is that correct?

2021-02-19 07:03 UTC, lwesterhof commented on semaphore/message_sender.py
> +                    return False
Yeah, looks like this could lead to trouble.

2021-02-19 17:23 UTC, eknoes commented
I was not aware of the id field before Finns comment on the issue, I'll add that as soon as I have the time for that! But that would still not solve the problem of getting a receipt for a second message before the first. I could just add an array of confirmed IDs which is checked before the socket is read. But I have no idea of how safe it is in terms of "thread safety" of the async framework. You have any idea? Otherwise I would try to read a bit about those issues in Python before implementing it, but that will take some time as I am quite busy for the next weeks.

2021-03-16 11:47 UTC, eknoes commented on semaphore/message_sender.py
> +        bot_message['id'] = self.signald_message_id
@lwesterhof Now I do use an incrementing value to identify the correct signald response as you requested

2021-03-16 11:51 UTC, eknoes reviewed
@lwesterhof Now I do use an incrementing value to identify the correct signald response as you requested

2021-03-16 12:06 UTC, eknoes commented
Sorry, I found some issues. I'll comment when I fixed them.

2021-03-16 12:57 UTC, eknoes commented
I ran my tests on the wrong commit, but now I fixed the comparison, tested it and it works fine :)

2021-04-02 16:28 UTC, eknoes commented
Is there any update or something I should do, to have this PR accepted?

2021-04-03 18:31 UTC, eknoes commented
I just merged the current main branch to avoid a merge conflict.

2021-04-15 16:53 UTC, lwesterhof approved these changes

2021-04-15 16:53 UTC, merged

2021-04-16 07:34 UTC, eknoes commented
Thanks for merging!